name: Run Pytest Tests and Generate Allure Report

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Install Allure
      run: |
        sudo apt-get update
        sudo apt-get install -y default-jre
        curl -o allure.zip -L https://github.com/allure-framework/allure2/releases/download/2.14.0/allure-2.14.0.zip
        unzip allure.zip -d /opt/
        sudo ln -s /opt/allure-2.14.0/bin/allure /usr/local/bin/allure

    - name: Debug - List files
      run: |
        echo "Listing all files in the repository"
        ls -R

    - name: Run Pytest and generate allure results
      run: |
        pytest automation/test_survey.py --alluredir=allure-results

    - name: Archive allure results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: allure-results
        path: allure-results
